[tool.poetry]
name = "klingon-subtitles"
version = "0.1.0"
description = "Make sure content always has subtitles"
authors = ["David Hooton <david@hooton.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
numpy = "^2.2.5"
ffmpeg-python = "^0.2.0"
pysrt = "^1.1.2"
srt = "^3.5.3"
watchdog = "^6.0.0"
moviepy = "^2.1.2"
transformers = "^4.51.3"
pyyaml = "^6.0.2"
numba = "^0.61.2"
llvmlite = "^0.44.0"
pyannote-audio = "^3.3.2"
tokenizers = "^0.21.1"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.5,<10.0.0"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.0"
klingon-tools = "^2.1.6"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
